language: go
sudo: false
go:
- 1.8
- 1.9
script:
- make test
env:
  global:
    secure: cHxC8cpFlo8qRkbC2Vbu3BmL963rclifLQDldhEdUxhjD5653rlyCaOEXHz0/VsyePvK9L9VUijsZmF0+/VLeDxC+UKWJ+NRJ6SDjzfG3pEW5WIg1HE7ZT2GYdvRfte/OEICjLbdyrl7vDhlQZpvAbYt/zLCGwkMjKalEE/ejkIb8p8zePBjDPmjD1RrRyzpVkexWyEyfSxYuxiKg3P9+XJkiuqYvrraYsVRb7g8JFu4DsLEY74vt315SdBtUPBZMWE0OcVV3dzkbpcfpXLC/f+uK/tXy8bG73JHgBHMwGbvcKz889dTZQV3nGGPEag52xigOB+V6PsfFzwS3mii2tM8/5vvf1pDjQ3QucQi4EQQwkG4C33ppygD30B8prHJHm+Hd4Q53wfAhQKqTNQ9ZgzWtwmjhiyHE1PPSr8hjeFwHC4sxEeqHlJb2ZhA8SJWyQDN8tPbRECH6uTlUCQ0Db3qlXdBpJUggdbreJhSQxCCUQ2x7Ik8ZdGBofISFzXhUBut/wJaLGMifIYnmpXX/5WBhdvyaPHw+TZLI3HxOm4U45ZrZCz5aZVyW168XFFzowLhUvcO1EUAoRpruQAghd53KjZyufWOa3fsCKGGrxEyxF+MWCb2/4pYohrndE2xE1Q6jGKK/iq2LUcaaOQywh//QGLmHQ0rZZpIkfDiNoc=
